version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests 
          command: dotnet test --no-build QuizRTapi.Tests
  deploy:  
    docker:
      - image: microsoft/dotnet:sdk
    # environment:
    #   AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - run:
          name: Koi Command Hai
          command: ls -a
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master